**This notebook is an exercise in the [SQL](https://www.kaggle.com/learn/intro-to-sql) course.  You can reference the tutorial at [this link](https://www.kaggle.com/dansbecker/getting-started-with-sql-and-bigquery).**

---

# Introduction

The first test of your new data exploration skills uses data describing crime in the city of Chicago.

Before you get started, run the following cell. It sets up the automated feedback system to review your answers.

In [1]:
# Set up feedack system
from learntools.core import binder
binder.bind(globals())
from learntools.sql.ex1 import *
print("Setup Complete")

Using Kaggle's public dataset BigQuery integration.
Setup Complete

Use the next code cell to fetch the dataset.

In [2]:
from google.cloud import bigquery

# Create a "Client" object
client = bigquery.Client()

# Construct a reference to the "chicago_crime" dataset
dataset_ref = client.dataset("chicago_crime", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

Using Kaggle's public dataset BigQuery integration.

In [3]:
dataset

Dataset(DatasetReference('bigquery-public-data', 'chicago_crime'))

# Exercises

### 1) Count tables in the dataset

How many tables are in the Chicago Crime dataset?

In [10]:
# Write the code you need here to figure out the answer
## first find the table list
tables_ref = client.list_tables(dataset)
tables     = list(tables_ref)
for table in tables:
    print(table.table_id)
print(len(tables))
## so there is only 1 table

crime
1

In [8]:
num_tables = 1  # Store the answer as num_tables and then run this cell

# Check your answer
q_1.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [9]:
#q_1.hint()
q_1.solution()

Solution:
```python

# List all the tables in the "chicago_crime" dataset
tables = list(client.list_tables(dataset))

# Print number of tables in the dataset
print(len(tables))

num_tables = 1

```

### 2) Explore the table schema

How many columns in the `crime` table have `TIMESTAMP` data?

In [14]:
# Write the code to figure out the answer
## get the table schema
## and then checks the column
## to find how many timestamp column are there
table_ref = dataset_ref.table("crime")
table     = client.get_table(table_ref)
table

Table(TableReference(DatasetReference('bigquery-public-data', 'chicago_crime'), 'crime'))

In [15]:
table.schema

[SchemaField('unique_key', 'INTEGER', 'REQUIRED', None, (), None),
 SchemaField('case_number', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('date', 'TIMESTAMP', 'NULLABLE', None, (), None),
 SchemaField('block', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('iucr', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('primary_type', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('description', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('location_description', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('arrest', 'BOOLEAN', 'NULLABLE', None, (), None),
 SchemaField('domestic', 'BOOLEAN', 'NULLABLE', None, (), None),
 SchemaField('beat', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('district', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('ward', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('community_area', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('fbi_code', 'STRING', 'NULLABLE', None, (), None),
 SchemaField('x_coordinate', 'FLOAT', 'NULLABLE', None, (), None),
 SchemaField('y_coordinate', 'FLOAT', 'NULLABLE', None, (), None),
 SchemaField('year', 'INTEGER', 'NULLABLE', None, (), None),
 SchemaField('updated_on', 'TIMESTAMP', 'NULLABLE', None, (), None),
 SchemaField('latitude', 'FLOAT', 'NULLABLE', None, (), None),
 SchemaField('longitude', 'FLOAT', 'NULLABLE', None, (), None),
 SchemaField('location', 'STRING', 'NULLABLE', None, (), None)]

In [16]:
num_timestamp_fields = 2 # Put your answer here

# Check your answer
q_2.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [21]:
#q_2.hint()
q_2.solution()

Solution:
```python

# Construct a reference to the "crime" table
table_ref = dataset_ref.table("crime")

# API request - fetch the table
table = client.get_table(table_ref)

# Print information on all the columns in the "crime" table in the "chicago_crime" dataset
print(table.schema)

num_timestamp_fields = 2

```

### 3) Create a crime map

If you wanted to create a map with a dot at the location of each crime, what are the names of the two fields you likely need to pull out of the `crime` table to plot the crimes on a map?

In [ ]:
# Write the code here to explore the data so you can find the answer

In [18]:
fields_for_plotting = ['latitude', 'longitude'] # Put your answers here

# Check your answer
q_3.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [23]:
q_3.hint()
q_3.solution()

Hint: Look at the table schema.  There are a couple options, but two of the fields are things commonly used to plot on maps. Both are `'FLOAT'` types. Use quotes around the field names in your answer.

Solution:
```python
fields_for_plotting = ['latitude', 'longitude']
```

Thinking about the question above, there are a few columns that appear to have geographic data. Look at a few values (with the `list_rows()` command) to see if you can determine their relationship.  Two columns will still be hard to interpret. But it should be obvious how the `location` column relates to `latitude` and `longitude`.

In [20]:
### Preview the first 10 lines of the "full" table
### get the table first
table_ref = dataset_ref.table("crime")
table    = client.get_table(table_ref)
client.list_rows(table,max_results=10).to_dataframe()

,unique_key,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,ward,community_area,fbi_code,x_coordinate,y_coordinate,year,updated_on,latitude,longitude,location
0,2445,HJ698541,2003-10-17 01:36:00+00:00,104XX S INDIANA AVE,0110,HOMICIDE,FIRST DEGREE MURDER,AUTO,False,False,...,9,49,01A,1179434.0,1835549.0,2003,2022-09-19 03:41:05+00:00,41.704027,-87.618556,"(41.704026818, -87.618555581)"
1,2456655,HH782677,2002-11-16 04:15:00+00:00,007XX E 103RD ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,VEHICLE NON-COMMERCIAL,True,True,...,9,50,02,1183056.0,1836832.0,2002,2018-02-10 03:50:01+00:00,41.707464,-87.605253,"(41.707464272, -87.605252859)"
2,9588438,HX238903,2014-04-27 01:20:00+00:00,104XX S COTTAGE GROVE AVE,0312,ROBBERY,ARMED:KNIFE/CUTTING INSTRUMENT,RESIDENCE,False,False,...,9,50,03,1182531.0,1835687.0,2014,2018-02-10 03:50:01+00:00,41.704334,-87.607211,"(41.70433441, -87.607210755)"
3,10746917,HZ508205,2016-11-08 09:08:00+00:00,106XX S WABASH AVE,0313,ROBBERY,ARMED: OTHER DANGEROUS WEAPON,RESIDENCE,True,False,...,9,49,03,1178459.0,1834450.0,2016,2018-10-19 04:08:40+00:00,41.701033,-87.622159,"(41.70103316, -87.622159067)"
4,11708787,JC289402,2019-06-02 06:20:00+00:00,002XX W 104TH ST,0313,ROBBERY,ARMED: OTHER DANGEROUS WEAPON,"SCHOOL, PUBLIC, GROUNDS",False,False,...,34,49,03,1176490.0,1835977.0,2019,2019-07-17 03:41:50+00:00,41.705268,-87.629323,"(41.705267858, -87.629323117)"
5,3755566,HL124505,2005-01-14 01:35:00+00:00,003XX E 103RD ST,031A,ROBBERY,ARMED: HANDGUN,ALLEY,False,False,...,9,49,03,1180531.0,1836752.0,2005,2018-02-28 03:56:25+00:00,41.707303,-87.614502,"(41.707302954, -87.614501821)"
6,2254267,HH530375,2002-07-23 04:45:00+00:00,001XX E 107TH ST,031A,ROBBERY,ARMED: HANDGUN,RESIDENCE,False,False,...,9,49,03,1179268.0,1834055.0,2002,2018-02-28 03:56:25+00:00,41.699931,-87.619209,"(41.699930855, -87.619208803)"
7,11394098,JB367363,2018-07-25 07:30:00+00:00,104XX S CORLISS AVE,031A,ROBBERY,ARMED: HANDGUN,STREET,False,False,...,9,50,03,1183422.0,1835942.0,2018,2018-08-01 03:55:43+00:00,41.705013,-87.603940,"(41.7050135, -87.603940179)"
8,10808337,JA107117,2017-01-07 10:35:00+00:00,0000X W 103RD ST,031A,ROBBERY,ARMED: HANDGUN,HOTEL/MOTEL,False,False,...,34,49,03,1177576.0,1836668.0,2017,2017-02-14 03:49:42+00:00,41.707140,-87.625326,"(41.707139627, -87.625325518)"
9,5649433,HN456123,2007-07-09 06:07:00+00:00,003XX E 103RD ST,031A,ROBBERY,ARMED: HANDGUN,PARKING LOT/GARAGE(NON.RESID.),False,False,...,9,49,03,1180256.0,1836744.0,2007,2018-02-28 03:56:25+00:00,41.707287,-87.615509,"(41.707287296, -87.615509109)"

# Keep going

You've looked at the schema, but you haven't yet done anything exciting with the data itself. Things get more interesting when you get to the data, so keep going to **[write your first SQL query](https://www.kaggle.com/dansbecker/select-from-where).**

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/intro-to-sql/discussion) to chat with other learners.*